version: '3.8'

services:
  github-backup:
    image: dzarlax/github-backup:latest
    environment:
      - OAUTH_TOKEN=${OAUTH_TOKEN}
      - ORG_URL=${ORG_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - backup:/backup
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  backup:
    driver: local
