version: '3.8'

services:
  github-backup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OAUTH_TOKEN=""
      - ORG_URL=""
      - CRON_SCHEDULE=""
    volumes:
      - backup:/backup
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  backup:
    driver: local
